# 기본 Hydra config 예시
# 환경 이름, 체크포인트 경로, PPO 파라미터 등 관리

env_name: CheetahRun
checkpoint_path: ./ppo_ckpt
headless: true  # headless 환경에서 실행 시 true, GUI 필요시 false
ppo:
  num_timesteps: 60000000
  # 추가 PPO 파라미터 필요시 여기에 작성
