_wandb:
    value:
        cli_version: 0.22.0
        e:
            q4p95p9f290emt61wcjq2thn0jr3uxo7:
                codePath: train_from_state.py
                codePathLocal: train_from_state.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1005867986944"
                        used: "532622368768"
                email: k1seul@snu.ac.kr
                executable: /home/seul/miniconda3/envs/mujoco/bin/python
                git:
                    commit: 6ba725bb8f7c705297e3d4a58e6c4aaebccf37eb
                    remote: git@github.com:k1seul/mujoco_playground.git
                gpu: NVIDIA GeForce RTX 4070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 5888
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070
                      uuid: GPU-e5125861-99d4-84b6-f7aa-2c977f1d120d
                host: SeulServer
                memory:
                    total: "67297267712"
                os: Linux-6.8.0-52-generic-x86_64-with-glibc2.39
                program: /home/seul/Desktop/project/mujoco/train_from_state.py
                python: CPython 3.11.13
                root: /home/seul/Desktop/project/mujoco
                startedAt: "2025-09-22T09:48:05.997768Z"
                writerId: q4p95p9f290emt61wcjq2thn0jr3uxo7
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 12
                - 45
                - 50
            "2":
                - 1
                - 12
                - 45
                - 50
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.13
            "5": 0.22.0
            "12": 0.22.0
            "13": linux-x86_64
checkpoint_path:
    value: ./ppo_ckpt
env_name:
    value: CartpoleBalance
headless:
    value: true
ppo:
    value:
        num_timesteps: 60000000
